### ISSUE TITLE
params is not being passed to downstream build

### ISSUE THREAD

**Issue by lopsch** [UKHomeOffice/drone-trigger#15]
Hi there,

I'm using both the latest versions of drone and drone-trigger and the following upstream test pipeline:
```
pipeline:
  deploy:
    image: quay.io/ukhomeofficedigital/drone-trigger
    drone_server: server
    drone_token: token
    repo: owner/repo
    deploy_to: testing
    params: FOO=BAR
    verbose: true
```
and the following downstream pipeline:
```
pipeline:
  deploy:
    image: alpine
    commands:
      - echo "$FOO"
```
.

The downstream pipeline is called from the upstream pipeline so drone-trigger generally works but the result of the deploy step is always:
```
1 + echo "$FOO" 0s
2

exit code 0
````
.
Even calling the pipeline directly via `drone deploy --param FOO=BAR owner/repo 1 testing` yields the same results. Do I need to enable/set some flags anywhere?

Thanks in advance.
